----------- 智能客服 -----------

-- 每日新增用户
SELECT DATE_FORMAT(CREATED_AT, '%Y-%m-%d') AS DAY,COUNT(*) FROM CAI.ACCOUNT GROUP BY DATE_FORMAT(CREATED_AT, '%Y-%m-%d') ORDER BY DAY;

-- 每日活跃用户
SELECT FROM_UNIXTIME(LEFT(CREATED,10), '%Y-%m-%d') AS DAY,COUNT(DISTINCT ACCOUNT_ID) FROM CAI.MSG_SUPPORT GROUP BY FROM_UNIXTIME(LEFT(CREATED,10), '%Y-%m-%d') ORDER BY DAY;

-- 每日问题数
SELECT FROM_UNIXTIME(LEFT(CREATED,10), '%Y-%m-%d') AS DAY,COUNT(*) FROM CAI.MSG_SUPPORT GROUP BY FROM_UNIXTIME(LEFT(CREATED,10), '%Y-%m-%d') ORDER BY DAY;

-- 智能客服消息详情
SELECT A1.PAYLOAD                                      AS question,
       A2.PAYLOAD                                      AS answer,
       FROM_UNIXTIME(LEFT(A1.CREATED, 10), '%Y-%m-%d') as 时间,
       SE.LOGINNAME                                    as 客户
FROM CAI.MSG_SUPPORT A1
         LEFT JOIN CAI.MSG_SUPPORT A2 ON `A1`.ID + 1 = A2.ID
         LEFT JOIN CAI.`ACCOUNT` CA ON A1.`ACCOUNT_ID` = CA.`ID`
         LEFT JOIN SHP.SHP_USER SE ON CA.`GKS_USER_ID` = SE.`ID`
WHERE A1.CREATED BETWEEN '1737648000000' AND '1738857600000'
  AND A1.`SOURCE_FROM` = 'CLIENT';


----------- 商务助手 -----------

-- 群总数
SELECT COUNT(DISTINCT(`ROOM_ID`)) FROM `MSG_WEWORK` WHERE `ROOM_ID` != '';
2792

-- 每周日活
SELECT FROM_UNIXTIME(LEFT(CREATED, 10), '%Y-%m-%d') AS '日期',
       COUNT(DISTINCT ACCOUNT_ID)                   AS '每日活跃用户总数',
       COUNT(BIZ_ID)                                   '每日问题总数'
FROM CAI.MSG_ASSISTANT
WHERE SOURCE_FROM = 'CLIENT'
  AND CREATED BETWEEN '1740326400000' AND '1740931200000'
GROUP BY FROM_UNIXTIME(LEFT(CREATED, 10), '%Y-%m-%d');

-- 每周活跃榜
SELECT SE.REALNAME, MS.MESSAGE_COUNT
FROM (SELECT ACCOUNT_ID, COUNT(ID) AS MESSAGE_COUNT
      FROM CAI.MSG_ASSISTANT
      WHERE SOURCE_FROM = 'CLIENT'
        AND CREATED BETWEEN '1740326400000' AND '1740931200000'
      GROUP BY ACCOUNT_ID
      ORDER BY MESSAGE_COUNT DESC) MS
         LEFT JOIN CAI.ACCOUNT A ON MS.ACCOUNT_ID = A.ID
         LEFT JOIN SHP.SHP_EMPLOYEE SE ON A.GKS_USER_ID = SE.ID;

-- 商务助手消息详情
SELECT A1.PAYLOAD                                      AS question,
       A2.PAYLOAD                                      AS answer,
       FROM_UNIXTIME(LEFT(A1.CREATED, 10), '%Y-%m-%d') as 时间,
       SE.`REALNAME`                                   as 商务
FROM CAI.MSG_ASSISTANT A1
         LEFT JOIN CAI.MSG_ASSISTANT A2 ON `A1`.`BIZ_ID` = A2.QUOTE_MSG_ID
         LEFT JOIN CAI.`ACCOUNT` CA ON A1.`ACCOUNT_ID` = CA.`ID`
         LEFT JOIN SHP.`SHP_EMPLOYEE` SE ON CA.`GKS_USER_ID` = SE.`ID`
WHERE A1.CREATED BETWEEN '1740326400000' AND '1740931200000'
  AND A1.`SOURCE_FROM` = 'CLIENT'
  ORDER BY CA.ID,`A1`.`CREATED`;
