-- 查询审批单
SELECT * FROM APV.APV_APPLY WHERE REFERENCE_NO = 'CLAP20240116115846224';
-- 查询授信审批记录
SELECT * FROM `CRD`.`CRD_CREDIT_APPROVAL_RECORD`  WHERE `APPLY_NO` = 'CLAP20240116115846224';

SELECT CCAR.ID, CCAR.SHOP_ID
FROM CRD.CRD_CREDIT_APPROVAL_RECORD CCAR
         LEFT JOIN APV.APV_APPLY AP ON CCAR.APPLY_NO = AP.REFERENCE_NO
-- 审批系统已审批
WHERE AP.STATUS = 20
-- 信用系统，推送中  
  AND CCAR.STATUS = 20;