SELECT PO.*
FROM FND.`FND_BILL_ALIPAY` FBA
         LEFT JOIN PMT.`PMT_PAYMENT_HISTORY` PPH ON FBA.REFERENCE_ID = PPH.ID
         LEFT JOIN PMT.`PMT_ORDER` PO ON PO.PAYMENT_ID = PPH.PAYMENT_ID
WHERE FBA.BILL_NO = 20230516195263480;