-- 查询出库单是否重复
SELECT
  SO.ORDER_NO
FROM
  ODR.ODR_ORDER O
  LEFT JOIN IVT.SAS_IVT_STOCK_OUT SO ON O.ORDER_NO = SO.ORDER_NO
WHERE
  O.CREATED_AT > '2023-03-08 00:00:00'
  AND O.CHANNEL_ID =1
  AND O.SOURCE_TYPE = 10
  AND SO.IS_DELETED = 0
  AND SO.PARENT_MODE = 0
  AND SO.TYPE IN (11)
  AND SO.PLATFORM_SOURCE = 20
  AND SO.STATUS = 35
  AND SO.`CREATED_BY`  = 0
GROUP BY SO.ORDER_NO
HAVING
  COUNT(*) > 1;

-- 查询订单过期时间
SELECT O.ID,
       O.`SHOP_ID`,
       O.`ORDER_NO`,
       O.`CREATED_AT`,
       date_add(O.`CREATED_AT`, interval SC.PAY_INTERVAL second) AS EXP
FROM `ODR_ORDER` O
         LEFT JOIN SHP.`SHP_COMPANY` SC ON O.`COMPANY_ID` = SC.`ID`
WHERE O.`SHOP_ID` != 9
  AND O.`IS_DELETED` = 0
  AND O.`PARENT_ORDER_ID` = 0
  AND O.`CREATED_AT` > '2023-01-01 00:00:00'
  AND O.`ORDER_STATUS` = 80
  AND O.`UPDATED_BY` = 0
  AND O.`UPDATED_AT` BETWEEN '2023-03-24 20:00:00' AND '2023-03-24 20:40:00'
  AND date_add(O.`CREATED_AT`, interval SC.PAY_INTERVAL second) > '2023-03-27 00:00:00';