-- 导出客户积分
SELECT SC.NAME             AS 客户名称,
       PAP.AVAILABLE_POINT AS 可用积分,
       PAP.FROZEN_POINT    AS 冻结积分,
       SE.REALNAME         AS 商务,
       SE2.REALNAME        AS 销售
FROM PNT.PNT_ACCOUNT_POINT PAP
         LEFT JOIN SHP.SHP_COMPANY SC ON SC.ID = PAP.COMPANY_ID
         LEFT JOIN SHP.SHP_EMPLOYEE SE ON SC.BUSINESS_ID = SE.ID
         LEFT JOIN SHP.SHP_EMPLOYEE SE2 ON SC.SALES_ID = SE2.ID
WHERE PAP.SHOP_ID = 9
  AND PAP.IS_DELETED = 0
  AND SC.IS_DELETED = 0;

-- 导出商户积分
SELECT SC.NAME             AS 客户名称,
       PAP.AVAILABLE_POINT AS 可用积分,
       PAP.FROZEN_POINT    AS 冻结积分,
       SE.REALNAME         AS 商务,
       SE2.REALNAME        AS 销售
FROM PPNT.PPNT_ACCOUNT_POINT PAP
         LEFT JOIN SHP.SHP_COMPANY SC ON SC.SHOP_ID = PAP.SHOP_ID AND IS_SELLER = 1
         LEFT JOIN SHP.SHP_EMPLOYEE SE ON SC.BUSINESS_ID = SE.ID
         LEFT JOIN SHP.SHP_EMPLOYEE SE2 ON SC.SALES_ID = SE2.ID
WHERE PAP.IS_DELETED = 0
  AND SC.IS_DELETED = 0;


-- 总开票数
SELECT DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m') AS MONTH, COUNT(*)
FROM FNC.FNC_INVOICE_OUT
WHERE INVOICE_OUT_TIME > '2024-09-01 00:00:00'
  AND STATUS IN (50, 60)
  AND SHOP_ID = 9
GROUP BY DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m')
ORDER BY MONTH;

-- 一单一票数
SELECT DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m') AS MONTH, COUNT(*)
FROM FNC.FNC_INVOICE_OUT
WHERE INVOICE_OUT_TIME > '2024-09-01 00:00:00'
  AND STATUS IN (50, 60)
  AND IS_MERGE_INVOICE = 0
  AND SHOP_ID = 9
GROUP BY DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m')
ORDER BY MONTH;

-- 总客户数
SELECT DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m') AS MONTH, COUNT(DISTINCT COMPANY_ID)
FROM FNC.FNC_INVOICE_OUT
WHERE INVOICE_OUT_TIME > '2024-09-01 00:00:00'
  AND STATUS IN (50, 60)
  AND SHOP_ID = 9
GROUP BY DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m')
ORDER BY MONTH;

-- 一单一票客户数
SELECT DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m') AS MONTH, COUNT(DISTINCT COMPANY_ID)
FROM FNC.FNC_INVOICE_OUT
WHERE INVOICE_OUT_TIME > '2024-09-01 00:00:00'
  AND STATUS IN (50, 60)
  AND SHOP_ID = 9
  AND IS_MERGE_INVOICE = 0
GROUP BY DATE_FORMAT(INVOICE_OUT_TIME, '%Y-%m')
ORDER BY MONTH;


-- 查询明细开票金额与单据金额不一致数据
SELECT FIO.ID                   AS '开票单id',
       FIO.INVOICE_OUT_NO       AS '开票单号',
       FIO.AMOUNT               AS '单据金额',
       FIOD.AMOUNT              AS '明细总金额',
       FIO.AMOUNT - FIOD.AMOUNT AS '差异金额'
FROM (SELECT D.INVOICE_OUT_ID, SUM(TOTAL_AMOUNT) AMOUNT
      FROM FNC.FNC_INVOICE_OUT_DETAIL D
               LEFT JOIN FNC.FNC_INVOICE_OUT F ON F.ID = D.INVOICE_OUT_ID
      WHERE F.IS_DELETED = 0
        AND D.IS_DELETED = 0
        AND D.STATUS = 10
        AND F.INVOICE_OUT_NO IN ('SI-1120240926343242344')
      GROUP BY INVOICE_OUT_ID) FIOD
         LEFT JOIN FNC.FNC_INVOICE_OUT FIO ON FIOD.INVOICE_OUT_ID = FIO.ID;
查询开票明细数量与出库不一致数据
SELECT SOD.ID, SOD.INVOICED_QUANTITY, FIOD.QUANTITY
FROM (
         SELECT STOCK_OUT_DETAIL_ID, SUM(QUANTITY) QUANTITY
         FROM PFNC.FNC_INVOICE_OUT_DETAIL
         WHERE IS_DELETED = 0
           AND STATUS = 10
           AND CREATED_AT > '2022-07-25'
         GROUP BY STOCK_OUT_DETAIL_ID) FIOD
         LEFT JOIN IVT.SAS_IVT_STOCK_OUT_DETAIL SOD ON FIOD.STOCK_OUT_DETAIL_ID = SOD.ID
WHERE FIOD.QUANTITY != SOD.INVOICED_QUANTITY;

-- 查询出库待开票数量不一致数据
SELECT
  SISO.`STOCK_OUT_NO` AS '出库单号',
  SISO.`CREATED_AT` AS '出库时间',
  SISO.SHIP_COMPLETE_AT AS '发货时间',
  SISO.ID AS '出库单id',
  SISOD.ORDER_NO AS '订单号',
  SISOD.ORDER_MODEL_ID AS '订单明细id',
  SISOD.`MATERIAL_NO` AS '订货号',
  SISOD.ID AS '出库明细',
  SISOD.PICKED_QUANTITY AS '已发货数量',
  SISOD.INVOICED_QUANTITY AS '开票数量',
  FIOD.QUANTITY AS '实际开票数量',
  SISO.`INVOICE_STATUS` AS '开票状态',
  SISOD.TOTAL_AMOUNT,
  FIOD.TOTAL_AMOUNT,
  FIOD.`ID`, SISOD.`INVOICED_AMOUNT` 
FROM
  IVT.SAS_IVT_STOCK_OUT SISO
  LEFT JOIN IVT.SAS_IVT_STOCK_OUT_DETAIL SISOD ON SISO.ID = SISOD.STOCK_OUT_ID
  LEFT JOIN FNC.FNC_INVOICE_OUT_DETAIL FIOD ON FIOD.STOCK_OUT_DETAIL_ID = SISOD.ID
WHERE
  SISO.IS_DELETED = 0
  AND SISO.PARENT_MODE = 0
  AND SISO.TYPE IN (11, 23)
  AND SISO.INVOICE_TYPE IN (1, 2, 5, 6)
  AND SISO.STATUS = 35
  AND FIOD.IS_DELETED = 0
  AND SISO.`ORDER_NO` = '202402268341423'

-- 查询出库明细货物来源采购时候的税率
SELECT S.STOCK_OUT_DETAIL_ID,
       MAX(P.TAX_RATE)
FROM IVT.SAS_IVT_STOCK_OUT_SHELF S
         LEFT JOIN IVT.SAS_IVT_SHELF_MODEL M ON S.SHELF_MODEL_ID = M.ID
         LEFT JOIN IVT.SAS_IVT_STOCK_IN_DETAIL_PURCHASE_DETAIL P ON P.STOCK_IN_DETAIL_ID = M.STOCK_IN_DETAIL_ID
WHERE S.STOCK_OUT_DETAIL_ID IN (4185624)
GROUP BY S.STOCK_OUT_DETAIL_ID;