-- 自营客户
SELECT AC.`BALANCE_AVAILABLE`, IF(AC.`COMPANY_ID` = 0, SU.LOGINNAME, SC.NAME)
FROM ACC.`ACC_ACCOUNT` AC
         LEFT JOIN `SHP`.`SHP_COMPANY` SC ON AC.`COMPANY_ID` = SC.`ID`
         LEFT JOIN `SHP`.`SHP_USER` SU ON AC.`USER_ID` = SU.ID
WHERE AC.`IS_DELETED` = 0
  AND SC.IS_DELETED = 0
  AND SU.IS_DELETED = 0
  AND AC.`BALANCE_AVAILABLE` = 0
  AND AC.`SHOP_ID` = 9
  AND AC.ID NOT IN (SELECT DISTINCT `ACCOUNT_ID`
                    FROM ACC.`ACC_BALANCE_HISTORY`
                    WHERE `CREATED_AT` > '2022-01-01 00:00:00'
                      AND `ACCOUNT_ID` IN
                          (SELECT ID FROM ACC.`ACC_ACCOUNT` WHERE `BALANCE_AVAILABLE` = 0 AND `SHOP_ID` = 9));
-- 平台客户
SELECT AC.`BALANCE_AVAILABLE`, SC.NAME
FROM PACC.`PACC_ACCOUNT` AC
         LEFT JOIN `SHP`.`SHP_COMPANY` SC ON AC.`SHOP_ID` = SC.`SHOP_ID` AND SC.IS_SELLER = 1
WHERE AC.`IS_DELETED` = 0
  AND SC.IS_DELETED = 0
  AND AC.`BALANCE_AVAILABLE` = 0
  AND AC.DIRECTION = 2
  AND AC.ID NOT IN (SELECT DISTINCT PACC_ACCOUNT_ID
                    FROM PACC.PACC_ACCOUNT_BALANCE_RECORD
                    WHERE `CREATED_AT` > '2022-01-01 00:00:00'
                      AND PACC_ACCOUNT_ID IN
                          (SELECT ID FROM PACC.`PACC_ACCOUNT` WHERE `BALANCE_AVAILABLE` = 0));